specVersion: 1.0.0
name: acala-subql
version: 1.0.0
description: ''
repository: ''
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: 'wss://acala-polkadot.api.onfinality.io/public-ws'
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  chaintypes:
    file: './src/chain-types.js'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleExtrinsic
          kind: substrate/CallHandler
        - handler: handleBlock
          kind: substrate/BlockHandler